//
// GetWeatherData200ResponseSys.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWeatherData200ResponseSys: Codable, Hashable {

    public var type: Int?
    public var id: Int?
    public var country: String?
    public var sunrise: Int?
    public var sunset: Int?

    public init(type: Int? = nil, id: Int? = nil, country: String? = nil, sunrise: Int? = nil, sunset: Int? = nil) {
        self.type = type
        self.id = id
        self.country = country
        self.sunrise = sunrise
        self.sunset = sunset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case country
        case sunrise
        case sunset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(sunrise, forKey: .sunrise)
        try container.encodeIfPresent(sunset, forKey: .sunset)
    }
}

