//
// GetWeatherForecast200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWeatherForecast200Response: Codable, Hashable {

    public var cod: String?
    public var message: Double?
    public var cnt: Int?
    public var list: [GetWeatherForecast200ResponseListInner]?
    public var city: GetWeatherForecast200ResponseCity?

    public init(cod: String? = nil, message: Double? = nil, cnt: Int? = nil, list: [GetWeatherForecast200ResponseListInner]? = nil, city: GetWeatherForecast200ResponseCity? = nil) {
        self.cod = cod
        self.message = message
        self.cnt = cnt
        self.list = list
        self.city = city
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cod
        case message
        case cnt
        case list
        case city
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cod, forKey: .cod)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(cnt, forKey: .cnt)
        try container.encodeIfPresent(list, forKey: .list)
        try container.encodeIfPresent(city, forKey: .city)
    }
}

