//
// GetWeatherForecast200ResponseListInnerMain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWeatherForecast200ResponseListInnerMain: Codable, Hashable {

    public var temp: Double?
    public var feelsLike: Double?
    public var tempMin: Double?
    public var tempMax: Double?
    public var pressure: Int?
    public var seaLevel: Int?
    public var grndLevel: Int?
    public var humidity: Int?
    public var tempKf: Double?

    public init(temp: Double? = nil, feelsLike: Double? = nil, tempMin: Double? = nil, tempMax: Double? = nil, pressure: Int? = nil, seaLevel: Int? = nil, grndLevel: Int? = nil, humidity: Int? = nil, tempKf: Double? = nil) {
        self.temp = temp
        self.feelsLike = feelsLike
        self.tempMin = tempMin
        self.tempMax = tempMax
        self.pressure = pressure
        self.seaLevel = seaLevel
        self.grndLevel = grndLevel
        self.humidity = humidity
        self.tempKf = tempKf
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case temp
        case feelsLike = "feels_like"
        case tempMin = "temp_min"
        case tempMax = "temp_max"
        case pressure
        case seaLevel = "sea_level"
        case grndLevel = "grnd_level"
        case humidity
        case tempKf = "temp_kf"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(temp, forKey: .temp)
        try container.encodeIfPresent(feelsLike, forKey: .feelsLike)
        try container.encodeIfPresent(tempMin, forKey: .tempMin)
        try container.encodeIfPresent(tempMax, forKey: .tempMax)
        try container.encodeIfPresent(pressure, forKey: .pressure)
        try container.encodeIfPresent(seaLevel, forKey: .seaLevel)
        try container.encodeIfPresent(grndLevel, forKey: .grndLevel)
        try container.encodeIfPresent(humidity, forKey: .humidity)
        try container.encodeIfPresent(tempKf, forKey: .tempKf)
    }
}

