//
// GetWeatherData200ResponseClouds.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWeatherData200ResponseClouds: Codable, Hashable {

    public var all: Int?

    public init(all: Int? = nil) {
        self.all = all
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case all
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(all, forKey: .all)
    }
}

