//
// GetWeatherData200ResponseMain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWeatherData200ResponseMain: Codable, Hashable {

    public var temp: Double?
    public var feelsLike: Double?
    public var tempMin: Double?
    public var tempMax: Double?
    public var pressure: Int?
    public var humidity: Int?

    public init(temp: Double? = nil, feelsLike: Double? = nil, tempMin: Double? = nil, tempMax: Double? = nil, pressure: Int? = nil, humidity: Int? = nil) {
        self.temp = temp
        self.feelsLike = feelsLike
        self.tempMin = tempMin
        self.tempMax = tempMax
        self.pressure = pressure
        self.humidity = humidity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case temp
        case feelsLike = "feels_like"
        case tempMin = "temp_min"
        case tempMax = "temp_max"
        case pressure
        case humidity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(temp, forKey: .temp)
        try container.encodeIfPresent(feelsLike, forKey: .feelsLike)
        try container.encodeIfPresent(tempMin, forKey: .tempMin)
        try container.encodeIfPresent(tempMax, forKey: .tempMax)
        try container.encodeIfPresent(pressure, forKey: .pressure)
        try container.encodeIfPresent(humidity, forKey: .humidity)
    }
}

