//
// GetWeatherForecast200ResponseListInnerSys.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWeatherForecast200ResponseListInnerSys: Codable, Hashable {

    public var pod: String?

    public init(pod: String? = nil) {
        self.pod = pod
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pod
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pod, forKey: .pod)
    }
}

