//
// GetWeatherForecast200ResponseListInnerRain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWeatherForecast200ResponseListInnerRain: Codable, Hashable {

    public var _3h: Double?

    public init(_3h: Double? = nil) {
        self._3h = _3h
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _3h = "3h"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_3h, forKey: ._3h)
    }
}

