//
// WeatherResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WeatherResponse: Codable, Hashable {

    public var current: WeatherResponseCurrent?
    public var hourly: [WeatherResponseCurrent]?
    public var daily: [WeatherResponseCurrent]?

    public init(current: WeatherResponseCurrent? = nil, hourly: [WeatherResponseCurrent]? = nil, daily: [WeatherResponseCurrent]? = nil) {
        self.current = current
        self.hourly = hourly
        self.daily = daily
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case hourly
        case daily
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(current, forKey: .current)
        try container.encodeIfPresent(hourly, forKey: .hourly)
        try container.encodeIfPresent(daily, forKey: .daily)
    }
}

