//
// WeatherResponseCurrentWindMax.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WeatherResponseCurrentWindMax: Codable, Hashable {

    public var speed: Double?
    public var direction: Int?

    public init(speed: Double? = nil, direction: Int? = nil) {
        self.speed = speed
        self.direction = direction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case speed
        case direction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(speed, forKey: .speed)
        try container.encodeIfPresent(direction, forKey: .direction)
    }
}

