//
// WeatherResponseCurrentWind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WeatherResponseCurrentWind: Codable, Hashable {

    public var max: WeatherResponseCurrentWindMax?

    public init(max: WeatherResponseCurrentWindMax? = nil) {
        self.max = max
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case max
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(max, forKey: .max)
    }
}

